# Generated by Django 2.1.7 on 2019-05-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190506_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
