# Generated by Django 2.2.1 on 2019-05-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logined_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
