# Generated by Django 2.2.1 on 2019-05-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_logined_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
